// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/client/cert/client.go
//
// Generated by this command:
//
//	mockgen -source ./internal/client/cert/client.go -destination ./internal/client/cert/client_mock.go
//

// Package mock_certclient is a generated GoMock package.
package certclient

import (
	context "context"
	reflect "reflect"
	xdsmodels "xds_server/internal/models"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Cert mocks base method.
func (m *MockClient) Cert(ctx context.Context, domain string) (*xdsmodels.Cert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cert", ctx, domain)
	ret0, _ := ret[0].(*xdsmodels.Cert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cert indicates an expected call of Cert.
func (mr *MockClientMockRecorder) Cert(ctx, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cert", reflect.TypeOf((*MockClient)(nil).Cert), ctx, domain)
}

// CloseConn mocks base method.
func (m *MockClient) CloseConn() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseConn")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseConn indicates an expected call of CloseConn.
func (mr *MockClientMockRecorder) CloseConn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseConn", reflect.TypeOf((*MockClient)(nil).CloseConn))
}
