// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: route_server.proto

package routeserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RouteClient is the client API for Route service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouteClient interface {
	AllRoutes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Route_AllRoutesClient, error)
}

type routeClient struct {
	cc grpc.ClientConnInterface
}

func NewRouteClient(cc grpc.ClientConnInterface) RouteClient {
	return &routeClient{cc}
}

func (c *routeClient) AllRoutes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Route_AllRoutesClient, error) {
	stream, err := c.cc.NewStream(ctx, &Route_ServiceDesc.Streams[0], "/Route/AllRoutes", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeAllRoutesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Route_AllRoutesClient interface {
	Recv() (*AllRoutesResponse, error)
	grpc.ClientStream
}

type routeAllRoutesClient struct {
	grpc.ClientStream
}

func (x *routeAllRoutesClient) Recv() (*AllRoutesResponse, error) {
	m := new(AllRoutesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RouteServer is the server API for Route service.
// All implementations must embed UnimplementedRouteServer
// for forward compatibility
type RouteServer interface {
	AllRoutes(*emptypb.Empty, Route_AllRoutesServer) error
	mustEmbedUnimplementedRouteServer()
}

// UnimplementedRouteServer must be embedded to have forward compatible implementations.
type UnimplementedRouteServer struct {
}

func (UnimplementedRouteServer) AllRoutes(*emptypb.Empty, Route_AllRoutesServer) error {
	return status.Errorf(codes.Unimplemented, "method AllRoutes not implemented")
}
func (UnimplementedRouteServer) mustEmbedUnimplementedRouteServer() {}

// UnsafeRouteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouteServer will
// result in compilation errors.
type UnsafeRouteServer interface {
	mustEmbedUnimplementedRouteServer()
}

func RegisterRouteServer(s grpc.ServiceRegistrar, srv RouteServer) {
	s.RegisterService(&Route_ServiceDesc, srv)
}

func _Route_AllRoutes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RouteServer).AllRoutes(m, &routeAllRoutesServer{stream})
}

type Route_AllRoutesServer interface {
	Send(*AllRoutesResponse) error
	grpc.ServerStream
}

type routeAllRoutesServer struct {
	grpc.ServerStream
}

func (x *routeAllRoutesServer) Send(m *AllRoutesResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Route_ServiceDesc is the grpc.ServiceDesc for Route service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Route_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Route",
	HandlerType: (*RouteServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AllRoutes",
			Handler:       _Route_AllRoutes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "route_server.proto",
}
