# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/project/model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from proto.v1.route import model_pb2 as v1_dot_route_dot_model__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16v1/project/model.proto\x12\rproject_model\x1a\x14v1/route/model.proto\";\n\x07Project\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\"\n\x06routes\x18\x02 \x03(\x0b\x32\x12.route_model.Routeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.project.model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_PROJECT']._serialized_start = 63
    _globals['_PROJECT']._serialized_end = 122
# @@protoc_insertion_point(module_scope)
