# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/project/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from proto.v1.project import model_pb2 as v1_dot_project_dot_model__pb2
from proto.v1.route import model_pb2 as v1_dot_route_dot_model__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18v1/project/service.proto\x12\x0fproject_service\x1a\x16v1/project/model.proto\x1a\x14v1/route/model.proto\"%\n\x15GetProjectInfoRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\"A\n\x16GetProjectInfoResponse\x12\'\n\x07project\x18\x01 \x01(\x0b\x32\x16.project_model.Project\"H\n\x15\x41\x64\x64ProjectInfoRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12!\n\x05route\x18\x02 \x01(\x0b\x32\x12.route_model.Route\"A\n\x16\x41\x64\x64ProjectInfoResponse\x12\'\n\x07project\x18\x01 \x01(\x0b\x32\x16.project_model.Project2\xd6\x01\n\x0eProjectService\x12\x61\n\x0eGetProjectInfo\x12&.project_service.GetProjectInfoRequest\x1a\'.project_service.GetProjectInfoResponse\x12\x61\n\x0e\x41\x64\x64ProjectInfo\x12&.project_service.AddProjectInfoRequest\x1a\'.project_service.AddProjectInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.project.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_GETPROJECTINFOREQUEST']._serialized_start = 91
    _globals['_GETPROJECTINFOREQUEST']._serialized_end = 128
    _globals['_GETPROJECTINFORESPONSE']._serialized_start = 130
    _globals['_GETPROJECTINFORESPONSE']._serialized_end = 195
    _globals['_ADDPROJECTINFOREQUEST']._serialized_start = 197
    _globals['_ADDPROJECTINFOREQUEST']._serialized_end = 269
    _globals['_ADDPROJECTINFORESPONSE']._serialized_start = 271
    _globals['_ADDPROJECTINFORESPONSE']._serialized_end = 336
    _globals['_PROJECTSERVICE']._serialized_start = 339
    _globals['_PROJECTSERVICE']._serialized_end = 553
# @@protoc_insertion_point(module_scope)
