# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.v1.domain import service_pb2 as v1_dot_domain_dot_service__pb2


class DomainServiceStub(object):
    """Missing associated documentation comment in .proto file."""
    
    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDomainsPool = channel.unary_unary(
            '/domain.DomainService/GetDomainsPool',
            request_serializer=v1_dot_domain_dot_service__pb2.GetDomainsPoolRequest.SerializeToString,
            response_deserializer=v1_dot_domain_dot_service__pb2.GetDomainsPoolResponse.FromString,
        )


class DomainServiceServicer(object):
    """Missing associated documentation comment in .proto file."""
    
    def GetDomainsPool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DomainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetDomainsPool': grpc.unary_unary_rpc_method_handler(
            servicer.GetDomainsPool,
            request_deserializer=v1_dot_domain_dot_service__pb2.GetDomainsPoolRequest.FromString,
            response_serializer=v1_dot_domain_dot_service__pb2.GetDomainsPoolResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'domain.DomainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class DomainService(object):
    """Missing associated documentation comment in .proto file."""
    
    @staticmethod
    def GetDomainsPool(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(request, target, '/domain.DomainService/GetDomainsPool',
                                             v1_dot_domain_dot_service__pb2.GetDomainsPoolRequest.SerializeToString,
                                             v1_dot_domain_dot_service__pb2.GetDomainsPoolResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
