# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/domain/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from proto.v1.domain import model_pb2 as v1_dot_domain_dot_model__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17v1/domain/service.proto\x12\x06\x64omain\x1a\x15v1/domain/model.proto\"\x17\n\x15GetDomainsPoolRequest\"9\n\x16GetDomainsPoolResponse\x12\x1f\n\x07\x64omains\x18\x01 \x03(\x0b\x32\x0e.domain.Domain2`\n\rDomainService\x12O\n\x0eGetDomainsPool\x12\x1d.domain.GetDomainsPoolRequest\x1a\x1e.domain.GetDomainsPoolResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.domain.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_GETDOMAINSPOOLREQUEST']._serialized_start = 58
    _globals['_GETDOMAINSPOOLREQUEST']._serialized_end = 81
    _globals['_GETDOMAINSPOOLRESPONSE']._serialized_start = 83
    _globals['_GETDOMAINSPOOLRESPONSE']._serialized_end = 140
    _globals['_DOMAINSERVICE']._serialized_start = 142
    _globals['_DOMAINSERVICE']._serialized_end = 238
# @@protoc_insertion_point(module_scope)
