# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/route/model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from proto.v1.subdomain import model_pb2 as v1_dot_subdomain_dot_model__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14v1/route/model.proto\x12\x0broute_model\x1a\x18v1/subdomain/model.proto\"J\n\x05Route\x12\x11\n\ttarget_ip\x18\x01 \x01(\t\x12.\n\nsubdomains\x18\x02 \x03(\x0b\x32\x1a.subdomain_model.Subdomainb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.route.model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_ROUTE']._serialized_start = 63
    _globals['_ROUTE']._serialized_end = 137
# @@protoc_insertion_point(module_scope)
