# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/subdomain/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from proto.v1.subdomain import model_pb2 as v1_dot_subdomain_dot_model__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1av1/subdomain/service.proto\x12\x11subdomain_service\x1a\x18v1/subdomain/model.proto\"\x1e\n\x1cGetOccupiedSubdomainsRequest\"O\n\x1dGetOccupiedSubdomainsResponse\x12.\n\nsubdomains\x18\x01 \x03(\x0b\x32\x1a.subdomain_model.Subdomain2\x8e\x01\n\x10SubdomainService\x12z\n\x15GetOccupiedSubdomains\x12/.subdomain_service.GetOccupiedSubdomainsRequest\x1a\x30.subdomain_service.GetOccupiedSubdomainsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.subdomain.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_GETOCCUPIEDSUBDOMAINSREQUEST']._serialized_start = 75
    _globals['_GETOCCUPIEDSUBDOMAINSREQUEST']._serialized_end = 105
    _globals['_GETOCCUPIEDSUBDOMAINSRESPONSE']._serialized_start = 107
    _globals['_GETOCCUPIEDSUBDOMAINSRESPONSE']._serialized_end = 186
    _globals['_SUBDOMAINSERVICE']._serialized_start = 189
    _globals['_SUBDOMAINSERVICE']._serialized_end = 331
# @@protoc_insertion_point(module_scope)
