# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/objects.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/objects.proto\x12\x07objects\"B\n\x05Route\x12\x11\n\ttarget_ip\x18\x01 \x01(\t\x12&\n\nsubdomains\x18\x02 \x03(\x0b\x32\x12.objects.Subdomain\"\x16\n\x06\x44omain\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x17\n\x15GetDomainsPoolRequest\":\n\x16GetDomainsPoolResponse\x12 \n\x07\x64omains\x18\x01 \x03(\x0b\x32\x0f.objects.Domain\"\x19\n\tSubdomain\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\x1cGetOccupiedSubdomainsRequest\"G\n\x1dGetOccupiedSubdomainsResponse\x12&\n\nsubdomains\x18\x01 \x03(\x0b\x32\x12.objects.Subdomain\"7\n\x07Project\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x1e\n\x06routes\x18\x02 \x03(\x0b\x32\x0e.objects.Route\"%\n\x15GetProjectInfoRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\";\n\x16GetProjectInfoResponse\x12!\n\x07project\x18\x01 \x01(\x0b\x32\x10.objects.Project\"D\n\x15\x41\x64\x64ProjectInfoRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x1d\n\x05route\x18\x02 \x01(\x0b\x32\x0e.objects.Route\";\n\x16\x41\x64\x64ProjectInfoResponse\x12!\n\x07project\x18\x01 \x01(\x0b\x32\x10.objects.Project2b\n\rDomainService\x12Q\n\x0eGetDomainsPool\x12\x1e.objects.GetDomainsPoolRequest\x1a\x1f.objects.GetDomainsPoolResponse2z\n\x10SubdomainService\x12\x66\n\x15GetOccupiedSubdomains\x12%.objects.GetOccupiedSubdomainsRequest\x1a&.objects.GetOccupiedSubdomainsResponse2\xb6\x01\n\x0eProjectService\x12Q\n\x0eGetProjectInfo\x12\x1e.objects.GetProjectInfoRequest\x1a\x1f.objects.GetProjectInfoResponse\x12Q\n\x0e\x41\x64\x64ProjectInfo\x12\x1e.objects.AddProjectInfoRequest\x1a\x1f.objects.AddProjectInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.objects_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROUTE']._serialized_start=32
  _globals['_ROUTE']._serialized_end=98
  _globals['_DOMAIN']._serialized_start=100
  _globals['_DOMAIN']._serialized_end=122
  _globals['_GETDOMAINSPOOLREQUEST']._serialized_start=124
  _globals['_GETDOMAINSPOOLREQUEST']._serialized_end=147
  _globals['_GETDOMAINSPOOLRESPONSE']._serialized_start=149
  _globals['_GETDOMAINSPOOLRESPONSE']._serialized_end=207
  _globals['_SUBDOMAIN']._serialized_start=209
  _globals['_SUBDOMAIN']._serialized_end=234
  _globals['_GETOCCUPIEDSUBDOMAINSREQUEST']._serialized_start=236
  _globals['_GETOCCUPIEDSUBDOMAINSREQUEST']._serialized_end=266
  _globals['_GETOCCUPIEDSUBDOMAINSRESPONSE']._serialized_start=268
  _globals['_GETOCCUPIEDSUBDOMAINSRESPONSE']._serialized_end=339
  _globals['_PROJECT']._serialized_start=341
  _globals['_PROJECT']._serialized_end=396
  _globals['_GETPROJECTINFOREQUEST']._serialized_start=398
  _globals['_GETPROJECTINFOREQUEST']._serialized_end=435
  _globals['_GETPROJECTINFORESPONSE']._serialized_start=437
  _globals['_GETPROJECTINFORESPONSE']._serialized_end=496
  _globals['_ADDPROJECTINFOREQUEST']._serialized_start=498
  _globals['_ADDPROJECTINFOREQUEST']._serialized_end=566
  _globals['_ADDPROJECTINFORESPONSE']._serialized_start=568
  _globals['_ADDPROJECTINFORESPONSE']._serialized_end=627
  _globals['_DOMAINSERVICE']._serialized_start=629
  _globals['_DOMAINSERVICE']._serialized_end=727
  _globals['_SUBDOMAINSERVICE']._serialized_start=729
  _globals['_SUBDOMAINSERVICE']._serialized_end=851
  _globals['_PROJECTSERVICE']._serialized_start=854
  _globals['_PROJECTSERVICE']._serialized_end=1036
# @@protoc_insertion_point(module_scope)
