# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/objects.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/objects.proto\x12\x07objects\"P\n\x05Route\x12\x11\n\ttarget_ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12&\n\nsubdomains\x18\x03 \x03(\x0b\x32\x12.objects.Subdomain\"\x16\n\x06\x44omain\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x17\n\x15GetDomainsPoolRequest\":\n\x16GetDomainsPoolResponse\x12 \n\x07\x64omains\x18\x01 \x03(\x0b\x32\x0f.objects.Domain\"\x19\n\tSubdomain\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\x1cGetOccupiedSubdomainsRequest\"G\n\x1dGetOccupiedSubdomainsResponse\x12&\n\nsubdomains\x18\x01 \x03(\x0b\x32\x12.objects.Subdomain\"7\n\x07Project\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x1e\n\x06routes\x18\x02 \x03(\x0b\x32\x0e.objects.Route\"%\n\x15GetProjectInfoRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\";\n\x16GetProjectInfoResponse\x12!\n\x07project\x18\x01 \x01(\x0b\x32\x10.objects.Project\"D\n\x15\x41\x64\x64ProjectInfoRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x1d\n\x05route\x18\x02 \x01(\x0b\x32\x0e.objects.Route\";\n\x16\x41\x64\x64ProjectInfoResponse\x12!\n\x07project\x18\x01 \x01(\x0b\x32\x10.objects.Project2b\n\rDomainService\x12Q\n\x0eGetDomainsPool\x12\x1e.objects.GetDomainsPoolRequest\x1a\x1f.objects.GetDomainsPoolResponse2z\n\x10SubdomainService\x12\x66\n\x15GetOccupiedSubdomains\x12%.objects.GetOccupiedSubdomainsRequest\x1a&.objects.GetOccupiedSubdomainsResponse2\xb6\x01\n\x0eProjectService\x12Q\n\x0eGetProjectInfo\x12\x1e.objects.GetProjectInfoRequest\x1a\x1f.objects.GetProjectInfoResponse\x12Q\n\x0e\x41\x64\x64ProjectInfo\x12\x1e.objects.AddProjectInfoRequest\x1a\x1f.objects.AddProjectInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.objects_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROUTE']._serialized_start=32
  _globals['_ROUTE']._serialized_end=112
  _globals['_DOMAIN']._serialized_start=114
  _globals['_DOMAIN']._serialized_end=136
  _globals['_GETDOMAINSPOOLREQUEST']._serialized_start=138
  _globals['_GETDOMAINSPOOLREQUEST']._serialized_end=161
  _globals['_GETDOMAINSPOOLRESPONSE']._serialized_start=163
  _globals['_GETDOMAINSPOOLRESPONSE']._serialized_end=221
  _globals['_SUBDOMAIN']._serialized_start=223
  _globals['_SUBDOMAIN']._serialized_end=248
  _globals['_GETOCCUPIEDSUBDOMAINSREQUEST']._serialized_start=250
  _globals['_GETOCCUPIEDSUBDOMAINSREQUEST']._serialized_end=280
  _globals['_GETOCCUPIEDSUBDOMAINSRESPONSE']._serialized_start=282
  _globals['_GETOCCUPIEDSUBDOMAINSRESPONSE']._serialized_end=353
  _globals['_PROJECT']._serialized_start=355
  _globals['_PROJECT']._serialized_end=410
  _globals['_GETPROJECTINFOREQUEST']._serialized_start=412
  _globals['_GETPROJECTINFOREQUEST']._serialized_end=449
  _globals['_GETPROJECTINFORESPONSE']._serialized_start=451
  _globals['_GETPROJECTINFORESPONSE']._serialized_end=510
  _globals['_ADDPROJECTINFOREQUEST']._serialized_start=512
  _globals['_ADDPROJECTINFOREQUEST']._serialized_end=580
  _globals['_ADDPROJECTINFORESPONSE']._serialized_start=582
  _globals['_ADDPROJECTINFORESPONSE']._serialized_end=641
  _globals['_DOMAINSERVICE']._serialized_start=643
  _globals['_DOMAINSERVICE']._serialized_end=741
  _globals['_SUBDOMAINSERVICE']._serialized_start=743
  _globals['_SUBDOMAINSERVICE']._serialized_end=865
  _globals['_PROJECTSERVICE']._serialized_start=868
  _globals['_PROJECTSERVICE']._serialized_end=1050
# @@protoc_insertion_point(module_scope)
